### ISSUE TITLE
React/RCTDefines.h' file not found

### ISSUE THREAD

**Issue by vinoth-am** [BonifyByForteil/react-native-matomo#47]
@lordkiz @DajePepo Getting below error after updating the react native matomo version (0.1.2).

![Screenshot 2020-03-04 at 5 17 54 PM](https://user-images.githubusercontent.com/20659936/75876921-98090c80-5e3c-11ea-8ab7-06e9ae436805.png)

**Comment by lordkiz** [comment]
@vinoth-am Which version of react-native are you currently using?

**Comment by vinoth-am** [comment]
react-native 0.61.5.

**Comment by lordkiz** [comment]
This is probably due to how files are imported within the `../node_modules/react-native/react/base` in `RN v0.61.5` (I am assuming you are using cocoapods)

A few things you can try until this is fixed:
1. If you have installed `react-native-matomo` manually, select `BNFMatomo` from the libraries folder to the left. Then select `BNFMatomo` target. In `Build Settings` after selecting BNFMatomo as your target, find `Header Search Paths` and add `${SRCROOT}/../../../ios/Pods/Headers` in the BNFMatomo target header search path.
After this, I expect your project to build. If you are deploying using CI/CD directly from your local environment, I don't expect you to have issues during your archiving step on CI. 

2. If you have installed `react-native-matomo` using cocoapods, an easy way is to patch `RNv0.61.5` using [patch-package](https://www.npmjs.com/package/patch-package).
a. In `node_modules/react-native/React/Base/RCTBridgeModule.h` replace `#import <React/RCTDefines.h>` with: 
```
#if __has_include("RCTDefines.h")
  #import "RCTDefines.h"
#else
  #import <React/RCTDefines.h>
#endif
```
You may need to patch `RCTAssert.h`, `RCTLog.h` and `RCTUtils.h` where the <> import styles were used.

**Comment by vinoth-am** [comment]
@lordkiz Alternate solution. Add **Header Search Paths** resolved my issue.

**Pods**-->**BNFMatomo**--> Search **Header Search Paths** --> Add **"${PODS_ROOT}/Headers"** -->Change to **recursive**

![Screenshot 2020-03-05 at 2 57 18 AM](https://user-images.githubusercontent.com/20659936/75925079-0e822a80-5e8e-11ea-88c4-778f06e0bdc9.png)

**Comment by lordkiz** [comment]
@vinoth-am good alternate solution

**Comment by noway** [comment]
> @lordkiz Alternate solution. Add **Header Search Paths** resolved my issue.
> 
> **Pods**-->**BNFMatomo**--> Search **Header Search Paths** --> Add **"${PODS_ROOT}/Headers"** -->Change to **recursive**
> 
> ![matomo](https://user-images.githubusercontent.com/20659936/102346845-8789e300-3fc5-11eb-91b9-2ddf7205fdb0.png)

This helped! Also make sure you are NOT using `use_frameworks!`
